### ISSUE TITLE
Running qwalk.py

### ISSUE THREAD

**Issue by sidneyholden1** [ctamon/quantum-walk-on-graphs#1]
Hi there,

I'm very new to GitHub so I'm not sure if this is where I should be commenting. But here goes:

I've finally managed to import pygame, but now when I try to run:

python3 qwalk.py

in the command line (python qwalk.py still won't import pygame), I get this error:

Traceback (most recent call last):
  File "qwalk.py", line 122, in <module>
    qwalk_me(A)
  File "qwalk.py", line 87, in qwalk_me
    pygame.draw.line(DISPLAYSURF, BLUE, Vertex[edge[0]], Vertex[edge[1]], thickness)
TypeError: 'map' object is not subscriptable

Any help would be much appreciated.

**Comment by sidneyholden1** [comment]
Just had to add list() to every map(...) i.e. list(map(...)).

The issue was that the syntax is different in Python 3. (what I'm now using).
